# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a311f9f5b0da425d458afeec3a14316c2fdae0dd628d04f2b2fe9c3f6cdf7468fd172b708a5d1f58f11f7ef08e3e03b3651176427674108e033be469c2b9187b

test:
  secret_key_base: 8879f1b055e85d6681f1a0a7ed1b3d1847ec6a26e46d028a4d999a67e6cbfc959fcd371b53b3529794ff85cfca9ea9c7433f9f7fee941a6b2ae5afb8313514ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
